version: "3.7"
services:

  database:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: OnlineCabBooking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  application:
    image: docker.normalizedsystems.org/nsapp/onlinecabbooking:latest
    depends_on:
      - database
    restart: unless-stopped
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: OnlineCabBooking
      DATABASE_USER: postgres
      DATABASE_PASS: postgres
    expose:
      - 80

volumes:
  postgres-data:
    driver: local
